version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - redis
      - database
    env_file: .env
    platform: linux/amd64 # to be able to run it on my M1 

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: musalasoft
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: